# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.CharField(max_length=128)),
            ],
        ),
    ]
